"""
@File    :sec_get.py
@Editor  : 百年
@Date    :2025/4/13 15:01 
"""
import time
from urllib.parse import urljoin
import csv
from selenium.webdriver import Chrome
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from lxml import etree
final_url_lst=[]
fp = open('./final_url_lst.csv','a+',encoding='utf-8',newline='')
writer = csv.writer(fp)
if fp.tell() == 0:
    writer.writerow(['最终分页连接',])
service = Service('../chromedriver.exe')
bro1 = Chrome(service=service)
url_lst = [#'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=临床神经病学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=传染病学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=呼吸系统',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=儿科',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=光学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=免疫学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=全科医学与补充医学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=公共卫生、环境卫生与职业卫生',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=兽医学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=内分泌学与代谢',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=初级卫生保健',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=力学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=动物学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=医学实验技术',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=医学：伦理',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=医学：信息',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=医学：内科',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=医学：法',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=医学：研究与实验',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=卫生保健与服务',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=危重病医学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=听力学与言语病理学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=声学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=外周血管病',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=外科',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=妇产科学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=学科教育',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=寄生虫学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=工程：生物医学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=康复医学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=微生物学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=心理学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=心脏和心血管系统',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=急救医学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=护理',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=数学与计算生物学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=数学跨学科应用',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=显微镜技术',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=有机化学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=材料科学：生物材料',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=影像医学与核医学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=核科学技术',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=植物科学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=毒理学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=泌尿学与肾脏学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=海洋与淡水生物学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=热带医学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=牙科与口腔外科',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=环境科学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=生化与分子生物学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=生化研究方法',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=生殖生物学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=生物多样性保护',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=生物学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=生物工程与应用微生物',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=生物物理',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=生理学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=男科学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=病毒学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=病理学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=皮肤病学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=真菌学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=眼科学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=神经成像',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=神经科学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=科学史与科学哲学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=移植',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=精神病学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=纳米科技',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=细胞与组织工程',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=细胞生物学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=统计学与概率论',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=老年医学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=耳鼻喉科学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=肿瘤学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=胃肠肝病学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=药学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=药物化学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=药物滥用',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=营养学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=血液学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=行为科学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=解剖学与形态学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=计算机：硬件',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=计算机：跨学科应用',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=过敏',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=运动科学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=遗传学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=风湿病学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=食品科技',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=骨科',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=麻醉学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=光学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=免疫学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=兽医学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=内分泌学与代谢',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=农业综合',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=农艺学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=动物学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=医学实验技术',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=医学：内科',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=医学：法',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=医学：研究与实验',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=发育生物学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=古生物学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=园艺',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=地球科学综合',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=奶制品与动物科学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=学科教育',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=工程：生物医学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=微生物学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=心理学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=数学与计算生物学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=昆虫学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=显微镜技术',
          # # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=材料科学：生物材料',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=核医学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=植物科学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=毒理学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=海洋与淡水生物学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=渔业',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=湖沼学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=物理：应用',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=环境科学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=生化与分子生物学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=生化研究方法',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=生态学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=生殖生物学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=生物多样性保护',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=生物学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=生物工程与应用微生物',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=生物物理',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=生理学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=病理学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=真菌学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=神经科学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=科学史与科学哲学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=纳米科技',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=细胞与组织工程',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=细胞生物学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=统计学与概率论',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=综合性期刊',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=老年医学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=营养学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=行为科学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=解剖学与形态学',
          # # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=运动科学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=进化生物学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=遗传学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=食品科技',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=骨科',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=鸟类学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=传染病学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=免疫学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=兽医学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=农业工程',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=农业经济与政策',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=农业综合',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=农艺学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=动物学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=医学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=研究与实验',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=园艺',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=土壤科学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=奶制品与动物科学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=微生物学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=昆虫学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=材料科学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=纸与木材',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=林学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=植物科学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=气象与大气科学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=水资源',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=海洋与淡水生物学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=渔业',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=环境科学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=生物工程与应用微生物',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=神经科学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=科学史与科学哲学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=绿色可持续发展技术',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=自然地理',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=营养学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=行为科学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=解剖学与形态学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=遗传学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=食品科技',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=农业综合',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=力学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=动物学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=古生物学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=土壤科学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=地球科学综合',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=工程：海洋',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=工程：环境',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=微生物学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=成像科学与照相技术',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=数学与计算生物学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=数学跨学科应用',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=林学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=核医学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=核科学技术',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=植物科学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=毒理学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=气象与大气科学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=水资源',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=海洋与淡水生物学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=渔业',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=湖沼学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=环境科学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=生化与分子生物学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=生态学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=生物多样性保护',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=生物学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=生物工程与应用微生物',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=真菌学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=矿业与矿物加工',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=纳米科技',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=绿色可持续发展技术',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=自然地理',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=行为科学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=进化生物学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=遗传学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=仪器仪表',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=光谱学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=全科医学与补充医学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=分析化学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=化学综合',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=声学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=学科教育',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=工程：化工',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=工程：土木',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=应用化学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=数学跨学科应用',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=无机化学与核化学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=晶体学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=有机化学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=材料科学：综合',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=核科学技术',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=海洋学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=热力学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=物理化学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=物理：凝聚态物理',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=物理：原子、分子和化学物理',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=物理：综合',
          # # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=环境科学',
          # # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=生化与分子生物学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=生化研究方法',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=生物工程与应用微生物',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=生物物理',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=电化学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=神经科学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=科学史与科学哲学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=绿色可持续发展技术',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=药物化学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=计算机：跨学科应用',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=高分子科学',
          # # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=仪器仪表',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=光学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=内分泌学与代谢',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=农业工程',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=农业综合',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=冶金工程',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=力学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=化学综合',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=医学实验技术',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=医学：信息',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=医学：研究与实验',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=园艺',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=地球化学与地球物理',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=地球科学综合',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=声学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=学科教育',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=工程：制造',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=工程：化工',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=工程：土木',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=工程：地质',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=工程：大洋',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=工程：宇航',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=工程：工业',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=工程：机械',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=工程：海洋',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=工程：环境',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=工程：生物医学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=工程：电子与电气',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=工程：石油',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=工程：综合',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=应用化学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=应用数学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=康复医学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=微生物学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=成像科学与照相技术',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=数学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=数学与计算生物学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=数学跨学科应用',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=显微镜技术',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=晶体学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=有机化学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=机器人学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=材料科学：复合',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=材料科学：生物材料',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=材料科学：硅酸盐',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=材料科学：纸与木材',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=材料科学：纺织',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=材料科学：综合',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=材料科学：膜',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=材料科学：表征与测试',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=林学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=核医学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=核科学技术',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=气象与大气科学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=水资源',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=热力学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=物理化学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=物理：凝聚态物理',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=物理：原子、分子和化学物理',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=物理：应用',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=物理：流体与等离子体',
          # # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=环境科学',
          # # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=生化与分子生物学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=生物工程与应用微生物',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=生物物理',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=电信学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=电化学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=皮肤病学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=矿业与矿物加工',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=矿物学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=神经科学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=科学史与科学哲学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=移植',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=纳米科技',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=细胞与组织工程',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=结构与建筑技术',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=统计学与概率论',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=综合性期刊',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=绿色可持续发展技术',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=能源与燃料',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=自动化与控制系统',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=药学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=营养学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=计算机：人工智能',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=计算机：信息系统',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=计算机：控制论',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=计算机：理论方法',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=计算机：硬件',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=计算机：跨学科应用',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=计算机：软件工程',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=运动科学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=运筹学与管理科学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=运输科技',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=逻辑学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=遥感',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=食品科技',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=高分子科学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=应用数学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=数学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=数学与计算生物学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=数学跨学科应用',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=物理：数学物理',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=科学史与科学哲学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=统计学与概率论',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=计算机：理论方法',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=计算机：跨学科应用',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=运筹学与管理科学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=逻辑学',
          # # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=仪器仪表',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=光学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=光谱学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=力学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=听力学与言语病理学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=声学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=天文与天体物理',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=学科教育',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=工程：电子与电气',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=应用数学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=数学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=数学跨学科应用',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=晶体学',
          # # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=材料科学：综合',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=材料科学：表征与测试',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=核科学技术',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=热力学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=物理化学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=物理：凝聚态物理',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=物理：原子、分子和化学物理',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=物理：应用',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=物理：数学物理',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=物理：核物理',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=物理：流体与等离子体',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=物理：粒子与场物理',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=物理：综合',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=生化研究方法',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=科学史与科学哲学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=纳米科技',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=高分子科学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=古生物学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=地球化学与地球物理',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=地球科学综合',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=地质学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=工程：地质',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=工程：大洋',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=工程：石油',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=成像科学与照相技术',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=数学跨学科应用',
          # # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=材料科学：综合',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=植物科学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=气象与大气科学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=水资源',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=海洋与淡水生物学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=海洋学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=湖沼学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=物理化学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=生物多样性保护',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=病理学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=矿业与矿物加工',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=矿物学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=科学史与科学哲学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=自然地理',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=进化生物学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=遥感',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=力学',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=地球化学与地球物理',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=地球科学综合',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=天文与天体物理',
          'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=数学跨学科应用',
          'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=气象与大气科学',
          'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=科学史与科学哲学',
          'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=兽医学',
          'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=农业经济与政策',
          'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=分析化学',
          'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=医学：伦理',
          'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=卫生保健与服务',
          'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=地球科学综合',
          'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=学科教育',
          'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=心理学',
          'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=数学',
          'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=数学跨学科应用',
          'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=神经科学',
          'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=科学史与科学哲学',
          'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=统计学与概率论',
          'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=综合性期刊',
          'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=绿色可持续发展技术',
          'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=计算机：跨学科应用',
          'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=运动科学',
          'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=运筹学与管理科学',
          'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=运输科技',
          'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=逻辑学',
          'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=农业经济与政策',
          'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=工程：制造',
          'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=工程：工业',
          'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=工程：综合',
          'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=应用数学',
          'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=数学跨学科应用',
          # 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=环境科学',
          'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=科学史与科学哲学',
          'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=统计学与概率论',
          'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=绿色可持续发展技术',
          'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=营养学',
          'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=行为科学',
          'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=计算机：信息系统',
          'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=计算机：跨学科应用',
          'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=运筹学与管理科学',
          'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=农艺学',
          'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=动物学',
          'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=工程：综合',
          'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=数学与计算生物学',
          'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=数学跨学科应用',
          'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=材料科学：综合',
          'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=生态学',
          'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=生物多样性保护',
          'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=科学史与科学哲学',
          'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=综合性期刊',
          'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=逻辑学']
# url = 'https://www.iikx.com/sci/list.html?classid=18&orderby=IF2024&ph=1&jcr21=%E4%B8%B4%E5%BA%8A%E7%A5%9E%E7%BB%8F%E7%97%85%E5%AD%A6'
for url in url_lst:
    time.sleep(2)
    print(url)
    bro1.get(url=url)
    time.sleep(3)
    page_ = bro1.page_source
    tree = etree.HTML(page_)
    # 创建一个用于存储得到的所有页面源码的列表
    all_page_lst = [page_]
    # 获取到总共有多少页

    page_number = tree.xpath('//ul[@class="el-pager"]/li[last()]/text()')
    page_num = int(page_number[0])
    print(page_num)

    # tips:发现页面是ajax请求，没办法直接遍历网页，所以这里直接定位到下一页按钮来进行访问
    for i in range(page_num + 1):  # tips:因为最后一页也要获取到，所以+1
        # tips:定位到下一页按钮
        nxt_btn = bro1.find_element(By.XPATH, '//button[@class="btn-next"]')
        #  tips:点击下一页按钮
        nxt_btn.click()
        # 然后停留几秒让网页加载
        time.sleep(3)
        all_page_lst.append(bro1.page_source)

    for page_text in all_page_lst:
        tree = etree.HTML(page_text)
        a_lst = tree.xpath('//table[@class="sci-table-info"]/tbody/tr/td[1][position()]/a/@href')
        for a in a_lst:
            full_url = 'https://www.iikx.com/' + a
            final_url = '\'' + full_url + '\''
            print(final_url)
            writer.writerow([final_url,])
    print('完毕')
fp.close()

# def get_every_url(url):
#     bro1.get(url=url)
#     time.sleep(3)
#     page_source = bro1.page_source
#     print(page_source)
#     tree = etree.HTML(page_source)
#     a_lst = tree.xpath('//table[@class="sci-table-info"]/tbody/tr/td[1][position()]/a/@href')
#     for a in a_lst:
#         # print(a)
#         full_url = 'https://www.iikx.com/'+a
#         print(full_url)
#     next_btn = bro1.find_element(By.XPATH,'//button[@class="btn-next"]')
#     next_btn.click()
#     time.sleep(2)
